### ISSUE TITLE
切换一次app功能就会失效 又恢复成密码输入模式了

### ISSUE THREAD

**Issue by johnsun3280** [kooritea/ForceGboardInputType#1]
如题，首先感谢作者的这么好的模块，非常有用，但是现在发现个问题，像在termux中，第一次是有效的，普通输入模式，但一旦切换出去，再切换回来又变成密码输入模式了，希望作者大佬能修改一下哈，再次感谢！

**Comment by kooritea** [comment]
我这里是第一次进入还是原来一样没有功能菜单，点一下语言切换的按钮就可以把功能菜单唤出来了，这个滞后再优化一下吧。

**Comment by kooritea** [comment]
[app-release.zip](https://github.com/kooritea/ForceGboardInputType/files/10397284/app-release.zip)
原来是少hook了一个位置，试试这个

**Comment by kooritea** [comment]
也不是研究过，只是这个输入类型是安卓的标准api所以比较好改，要改gboard的具体功能就比较复杂了😂

**Comment by kooritea** [comment]
在lsposed日志里看看inputType是多少

**Comment by kooritea** [comment]
[app-release.zip](https://github.com/kooritea/ForceGboardInputType/files/10636684/app-release.zip)
想了一下好像没有在url地址上输入中文逗号的场景，就算是搜索也可以用空格或者英文逗号代替，就不提交到仓库了，你直接用上面这个吧
